---
title: "SMB_Fitness_Growth"
author: "Joe Gunn"
date: "3/17/2021"
output: html_document
---

## Libraries needed for analysis
```{r setup, include=FALSE, include=FALSE}
library(readxl)
library(tidyverse)
library(cowplot)
library(riverdist)
library(sp)
library(popgraph)
library(gstudio)
library(ade4)
library(adegenet)
library(cowplot)
library(nlme)
library(poppr)
library(PopGenReport)
library(maps)
library(mapdata)
library(stringr)
library(rgdal)
library(sf)
library(ggsn)
library(raster)
library(lme4)
library(factoextra)
library(MASS)
library(logihist)
library(pophelper)
library(ggpubr)
library(DescTools)
library(vegan)
```

## Read in all data
```{r}
smbfit_data <- read_excel("../../raw_data/master_data/smbfit_master_data_working.xlsx")

smbfit_data <- smbfit_data %>%
  mutate(tl_alive = as.numeric(tl_alive))

#Change all character variables to factors
smbfit_data[sapply(smbfit_data, is.character)] <- lapply(smbfit_data[sapply(smbfit_data, is.character)], 
                                       as.factor)
```

## Read in genepop data
```{r}
smbfit_msat_data <- read_population("../../raw_data/genotype_data/smbfit_msat_genotypes.csv", type = "column", locus.columns = 2:29)

#Data Cleaning:

#Change categorical variables to factors
smbfit_msat_data$sample_id <- as.factor(smbfit_msat_data$sample_id)
```


```{r}
Ho_per_loc <- genetic_diversity(smbfit_msat_data, #calculate observed heterozygosity 
                                stratum = "sample_id", 
                                mode = c("Ho")) 


Ho_count_NA <- Ho_per_loc %>%
  mutate(Stratum = factor(Stratum)) %>%
  group_by(Stratum) %>%
  summarize(sum_na = sum(is.na(Ho)))

Ho_count_NA$sum_loc <- with(Ho_count_NA, 14 - sum_na)

Ho_per_loc_noNA <- Ho_per_loc %>%
  as.data.frame() %>%
  mutate(Stratum = factor(Stratum), Locus = factor(Locus)) %>%
  drop_na()
  
Ho_per_ind <- Ho_per_loc_noNA %>%
  group_by(Stratum) %>%
  summarize(tot_ho = sum(Ho)) 

Ho_per_ind <- Ho_per_ind %>%
  left_join(Ho_count_NA, by = "Stratum")


#Calculate per-individual Heterozygosity
Ho_per_ind$Ho <- with(Ho_per_ind, tot_ho/sum_loc)

colnames(Ho_per_ind)[1] <- "sample_id"

#join Ho data with age data

smbfit_data_het <- smbfit_data %>%
  left_join(Ho_per_ind, by = "sample_id")

smbfit_data_het$log10_wt <- with(smbfit_data_het, 3.2*log10(tl_alive) - 5.329)
smbfit_data_het$stand_wt <- with(smbfit_data_het, 10^log10_wt)
smbfit_data_het$tl_by_sl <- with(smbfit_data_het, tl_alive/sl)
smbfit_data_het$condition <- with(smbfit_data_het, mass_g/stand_wt)

smbfit_data_het_age2 <- smbfit_data_het %>%
  filter(consensus_age == "2")

ggplot(smbfit_data_het, aes(x = prop_nor, y = condition)) + 
  geom_point() +
  geom_smooth(method = "lm")

ggplot(smbfit_data_het, aes(x = hyb_status, y = )) + 
  geom_boxplot()

summary(lm(condition ~ Ho, smbfit_data_het))
```

```{r}

#Here, I am removing two outlier samples in which the difference between total length alive and total length dead was greater than -10 (which means that the total length dead was greater than the total length alive, which does not go along with the rest of the data. I am assuming these are the result of recorder or measurement error on these two samples)

smbfit_data_diff_outliers_removed <- smbfit_data[-c(64:65),]
smbfit_counts <- smbfit_data %>%
  group_by(hyb_status, sex) %>%
  count()

smbfit_m_f_averages <- smbfit_data %>%
  group_by(hyb_status, sex) %>%
  summarize(mean_nor_prop = mean(prop_nor))

pdf("/Users/joegunn/Desktop/Grad_School_Stuff/Research/Projects/Smallmouth_Bass_Fitness/visualization/growth_figures/preliminary_growth_curve.pdf", width=6, height=5)

ggplot(smbfit_data_diff_outliers_removed, aes(x = consensus_age, y = tl_alive, color = hyb_status)) +
  geom_point(size = 3, position = position_jitter(width = 0.3)) +
  geom_smooth() +
  theme_set(theme_cowplot(12)) +
  labs(x = "consensus age (years)", y = "total length alive (mm)") +
  scale_color_manual(values = c("firebrick3","navyblue")) +
  theme(axis.title = element_text(size = 15)) +
  theme(axis.text = element_text(size = 15))

dev.off()
```

## Run some preliminary data
```{r}


```

