---
title: "SMB_Fitness_STRUCTURE"
author: "Joe Gunn"
date: "3/17/2021"
output: html_document
---

## Libraries needed for analysis
```{r setup, include=FALSE, include = FALSE}
library(readxl)
library(tidyverse)
library(cowplot)
library(devtools)
library(pophelper)
library(genepopedit)
```

## Metadata
```{r}
smbfit_genetics_metadata <- read_excel("../../metadata/smbfit_genetics_metadata_no_hsyc.xlsx")

smbfit_genetics_metadata <- smbfit_genetics_metadata %>%
  mutate(sample_id = factor(sample_id),
         river_code = factor(river_code),
         range_id = factor(range_id),
         river = factor(river),
         pop = factor(pop))

smbfit_genetics_metadata <- column_to_rownames(smbfit_genetics_metadata, "NA")


```


```{r}
#Gather data
smbfit_sfiles <- list.files(path = "/Users/joegunn/Desktop/Grad_School_Stuff/Research/Projects/Smallmouth_Bass_Fitness/raw_data/structure_data/no_hsyc_500K_1M", full.names=T)

#Collate data for summary analysis
smbfit_slist <- readQ(smbfit_sfiles)
smbfit_tab <- tabulateQ(smbfit_slist)
smbfit_summary <- summariseQ(smbfit_tab)

#Plot summary data
options(scipen = 999)
smbfit_evanno_info <- evannoMethodStructure(smbfit_summary, returnplot = F) 


pdf("/Users/joegunn/Desktop/Grad_School_Stuff/Research/Projects/Smallmouth_Bass_Fitness/visualization/structure_results/structure_deltak.pdf", width = 6, height = 4)

ggplot(smbfit_evanno_info, aes(x = k, y = deltaK)) + 
  geom_point(size = 2) +
  geom_path() +
  theme_set(theme_cowplot(12)) +
  theme(axis.title = element_text(size = 15)) +
  theme(axis.text = element_text(size = 13)) +
  theme(axis.title.x = element_text(face = "italic")) +
  labs(x = "K", y = "DeltaK") +
  expand_limits(y = 30)

dev.off()

```

#Run clumpp
```{r}
clumppExport(smbfit_slist, parammode = 3, paramrep = 10000, useexe=T)

```


```{r}
smbfit_K2 <- readQ("../structure_analysis/smbfit_K2_nohsyc.txt")

#K = 2 Plot
plotQ(smbfit_K2,
      showindlab = F, 
      ordergrp = F,
      clustercol = c("deeppink2","deepskyblue"),
      showgrplab = F,
      showlegend = F, 
      showsp = F, 
      showdiv = T, 
      divsize = 2, 
      divtype = 1,
      divcol = "black",  
      grplabsize = 4, 
      legendkeysize = 15, 
      legendtextsize = 10, 
      linesize = 0.05, 
      pointsize = 4, 
      barbordercolour = "black",
      barbordersize = 0.1, 
      outputfilename = "../../visualization/structure_results/smbfit_structure",
      imgtype = "pdf",
      imgoutput = "sep",
      height = 10, width = 100)

```